### ISSUE TITLE
[new feature] Chrome Extension to make it easy to set routing context on requests

### ISSUE THREAD

**Issue by foxish** [signadot/community#13]
**New feature or functionality**
What would you like Signadot to do?

Currently, for users not making use of the preview URLs directly and working with their own ingress URLs, the recommendation is to use chrome extensions like [modheader](https://modheader.com/) / [requestly](https://requestly.io/). This work entails creating a chrome extension that is aware of RouteGroups, Sandboxes, etc to set headers with more ease on requests.

**Additional considerations**
Anything in particular to think about regarding this new feature?

**Comment by cwlbraa** [comment]
we'd love to have this integration. we're thinking about building this for ourselves internally, specifically to smooth out the process of deploy-then-copy-header-into-plugin, but it'd really make more sense as a first-party feature. preview URLs are challenging for us to make work from our existing frontend code.

**Comment by cwlbraa** [comment]
it's also worth noting that this would work through Ingresses, which signadot doesn't have the capability of forking directly.

**Comment by foxish** [comment]
This item is likely to improve the DevEx significantly for web UI based workflows, and is currently being planned for Q4.

**Comment by foxish** [comment]
This is now published (beta) in the Chrome webstore: https://chromewebstore.google.com/detail/signadot/aigejiccjejdeiikegdjlofgcjhhnkim
