### ISSUE TITLE
[new feature] TTL for Sandboxes

### ISSUE THREAD

**Issue by foxish** [signadot/community#2]
**New feature or functionality**
What would you like Signadot to do?

Implement the ability to automatically GC sandboxes after a certain amount of time elapses.
This helps ensure that resources don't live on for ever if they don't get cleaned up manually / via automation due to some error.

**Comment by scott-cotton** [comment]
This was implemented recently, closing.

All, please feel free to re-open if you feel the feature needs more discussion.
