### ISSUE TITLE
[new feature] support updates to sandboxes

### ISSUE THREAD

**Issue by foxish** [signadot/community#4]
**New feature or functionality**
What would you like Signadot to do?

Allow updates to sandboxes after creation. Currently all updates to sandboxes are rejected. 
This must allow for changing the configuration of a fork after it is created and observing the status of the updated sandbox as well.

**Additional considerations**
Anything in particular to think about regarding this new feature?

This is the basis for realizing features such as feature testing.

**Comment by scott-cotton** [comment]
v0.10.0 provides updates with the ability to update forks.  see https://docs.signadot.com/release-notes#2022-09-15.

**Comment by foxish** [comment]
Closing as completed
