### ISSUE TITLE
[bug] can't resolve SignadotRoute to fork of Rollout prod/metadata-service in cluster "cluster-name": can't get route info from cluster: the requested Pod port is not exposed through the baseline Service"

### ISSUE THREAD

**Issue by beejiujitsu** [signadot/community#5]
**Describe the bug**

`curl -H "signadot-api-key: ${{ secrets.SIGNADOT_API_KEY }}" $endpoint/api` outputs the following error:

> can't resolve SignadotRoute to fork of Rollout prod/metadata-service in cluster "cluster-name": can't get route info from cluster: the requested Pod port is not exposed through the baseline Service

And it did not trigger a Github workflow failure.

**To Reproduce**
1. Change pod configuration to listen on different port than expected in sandbox template endpoint
1. Create sandbox
2. Test sandbox using `curl -H "signadot-api-key: ${{ secrets.SIGNADOT_API_KEY }}" $endpoint/api`

**Expected behavior**

I expect "can't resolve SignadotRoute" errors to ultimately surface as a non-zero exit status in curl, causing the Github workflow step to fail.

**Observed behavior**

Step passed despite obvious error output.

**Additional context**

`$endpoint/api`: the `/api` is a path specific to the sandboxed service.

**Comment by beejiujitsu** [comment]
Hi foxish, thanks for replying. Yes, I concur on your diagnosis.  I've already fixed the problem.

The bigger issue here is Signadot didn't correctly signal to curl that it's a problem, which allowed the sandbox test step to falsely pass.

**Comment by foxish** [comment]
Ah, I see! I missed the point about the expected curl behavior. Makes sense. I'll check on our end if the error code is being propagated correctly. I think the `curl` might need a `--fail` flag to fail upon receiving a non-200 error code, but our examples & docs don't currently have this. 

```
curl --fail https://httpbin.org/status/500                                                                                                                                                                           
curl: (22) The requested URL returned error: 500 
```

**Comment by beejiujitsu** [comment]
Ah yes I forgot about that flag.

Will add, thank you.

As you say, the docs don't use it. Can we update them to reflect the correct usage?

> Ah, I see! I missed the point about the expected curl behavior. Makes sense. I'll check on our end if the error code is being propagated correctly. I think the `curl` will also need a `--fail` flag to fail upon receiving a non-200 error code, but our examples & docs don't currently have this. 
> 
> 
> 
> ```
> 
> curl --fail https://httpbin.org/status/500                                                                                                                                                                           
> 
> curl: (22) The requested URL returned error: 500 
> 
> ``` 
> 
> 
> 
>

**Comment by foxish** [comment]
Docs have been updated @beejiujitsu. Thanks for the bug report!

**Comment by beejiujitsu** [comment]
You’re welcome, thank you for updating the docs.

**Comment by scott-cotton** [comment]
closing as it seems this was addressed with the docs change.  Please feel free to re-open if you feel this needs further discussion.
