### ISSUE TITLE
[bug] Signadot chrome extension prompts user to login when logged in

### ISSUE THREAD

**Issue by foxish** [signadot/community#55]
**Describe the bug**
> On a few occasions we've seen the extension ask a user to login when they were indeed logged in to the signadot dashboard. Workaround has been to clear site data in the browser and re-login.

> I’ve been able to use Signadot previously ( a couple weeks ago) but now the extension just says “login to continue”. I’ve clicked the link and authenticated into the app but it still won’t update the extension.

**Expected behavior**
Not prompting to login

**Observed behavior**
Requires login

**Additional context**
Has been reported by multiple users

**Comment by jmsktm** [comment]
Have you found a way to repro it @foxish?

**Comment by foxish** [comment]
Fixed in https://www.signadot.com/docs/release-notes#chrome-extension-v120
