### ISSUE TITLE
[bug] Slack invite fails with Google auth

### ISSUE THREAD

**Issue by blaisep** [signadot/community#9]
**Describe the bug**
Slack fails to complete an invite using a Google account

**To Reproduce**
From the [Overview page](https://app.signadot.com/) 
select 
[slack community][(https://join.slack.com/t/signadotcommunity/shared_invite/zt-1estxm8pv-qfiaNfiFFCaW~eUlXsVoEQ)
and then select my google account

**Expected behavior**
I would expect to get an account on the signadotcommunity Slack

**Observed behavior**
Instead I get an error, "There was a glitch..."

**Additional context**
Screenie attached
![slack_oauth_error](https://user-images.githubusercontent.com/254456/200038557-58b1f5ce-e631-4163-ac75-486336478695.png)

**Comment by foxish** [comment]
Thanks for the bug report! Unfortunately, I wasn't able to replicate this on my end @blaisep. My current hypothesis is that this was perhaps a transient issue on the slack side? Are you able to check if this recurs?

**Comment by foxish** [comment]
Looks like this has been resolved now since we've not had any additional reports here regarding this.
